services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 28080:8080
    volumes:
      - ./config/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sprintdev
      POSTGRES_PASSWORD: sprintdev
      POSTGRES_DB: sprintdev
    ports:
      - 5432:5432